version: "3.9"
services:
  backend:
    build: ./backend
    container_name: whisper-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: whisper-frontend
    ports:
      - "8080:80"